jsonp1292353978803(
[
{"place":null,
"favorited":false,
"in_reply_to_screen_name":null,
"in_reply_to_status_id_str":null,
"id_str":"13305386329182209",
"geo":null,
"contributors":null,
"retweet_count":0,
"source":"\u003Ca href=\"http:\/\/bit.ly\" rel=\"nofollow\"\u003Ebitly\u003C\/a\u003E",
"in_reply_to_user_id_str":null,
"coordinates":null,
"retweeted":false,
"in_reply_to_status_id":null,
"user":{"follow_request_sent":null,
				"contributors_enabled":false,
				"description":"Official Twitter account of VA's Office of Enterprise Development in Product Development.",
				"show_all_inline_media":false,
				"geo_enabled":false,
				"favourites_count":0,
				"profile_link_color":"0084B4",
				"profile_sidebar_border_color":"C0DEED",
				"profile_image_url":"http:\/\/a3.twimg.com\/profile_images\/1014488319\/Official_VA_Seal_embossed_web_1-25in_normal.gif",
				"id_str":"158443688",
				"listed_count":11,
				"notifications":null,
				"profile_use_background_image":true,
				"followers_count":126,
				"location":"Washington, DC",
				"screen_name":"VA_OIT_PD",
				"profile_background_color":"C0DEED",
				"lang":"en",
				"statuses_count":324,
				"profile_background_image_url":"http:\/\/a3.twimg.com\/profile_background_images\/171951175\/twitt_bar_VA_Vert_PD.jpg",
				"url":"http:\/\/www.va.gov\/",
				"friends_count":149,
				"protected":false,
				"is_translator":false,
				"profile_text_color":"333333",
				"name":"VA OIT PD",
				"following":null,
				"profile_sidebar_fill_color":"DDEEF6",
				"id":158443688,
				"verified":false,
				"profile_background_tile":false,
				"time_zone":"Pacific Time (US & Canada)",
				"utc_offset":-28800,
				"created_at":"Tue Jun 22 18:19:52 +0000 2010"},
"in_reply_to_user_id":null,
"truncated":false,
"id":13305386329182209,
"text":"White House Details Sweeping Changes to Federal Computing - http:\/\/bit.ly\/hxxPNF #VA #Veterans #IT",
"created_at":"Fri Dec 10 18:53:45 +0000 2010"},

{"place":null,"favorited":false,"in_reply_to_screen_name":null,"in_reply_to_status_id_str":null,"id_str":"13232681424785410","geo":null,"contributors":null,"retweet_count":0,"source":"\u003Ca href=\"http:\/\/bit.ly\" rel=\"nofollow\"\u003Ebitly\u003C\/a\u003E","in_reply_to_user_id_str":null,"coordinates":null,"retweeted":false,"in_reply_to_status_id":null,"user":{"follow_request_sent":null,"contributors_enabled":false,"description":"Official Twitter account of VA's Office of Enterprise Development in Product Development.","show_all_inline_media":false,"geo_enabled":false,"favourites_count":0,"profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_image_url":"http:\/\/a3.twimg.com\/profile_images\/1014488319\/Official_VA_Seal_embossed_web_1-25in_normal.gif","id_str":"158443688","listed_count":11,"notifications":null,"profile_use_background_image":true,"followers_count":126,"location":"Washington, DC","screen_name":"VA_OIT_PD","profile_background_color":"C0DEED","lang":"en","statuses_count":324,"profile_background_image_url":"http:\/\/a3.twimg.com\/profile_background_images\/171951175\/twitt_bar_VA_Vert_PD.jpg","url":"http:\/\/www.va.gov\/","friends_count":149,"protected":false,"is_translator":false,"profile_text_color":"333333","name":"VA OIT PD","following":null,"profile_sidebar_fill_color":"DDEEF6","id":158443688,"verified":false,"profile_background_tile":false,"time_zone":"Pacific Time (US & Canada)","utc_offset":-28800,"created_at":"Tue Jun 22 18:19:52 +0000 2010"},
"in_reply_to_user_id":null,"truncated":false,"id":13232681424785410,"text":"Have you heard? The new acronym for the Nationwide Health Information Network is NwHIN.","created_at":"Fri Dec 10 14:04:51 +0000 2010"},

{"place":null,"favorited":false,"in_reply_to_screen_name":null,"in_reply_to_status_id_str":null,"id_str":"12936687013335041","geo":null,"contributors":null,"retweet_count":0,"source":"\u003Ca href=\"http:\/\/bit.ly\" rel=\"nofollow\"\u003Ebitly\u003C\/a\u003E","in_reply_to_user_id_str":null,"coordinates":null,"retweeted":false,"in_reply_to_status_id":null,"user":{"follow_request_sent":null,"contributors_enabled":false,"description":"Official Twitter account of VA's Office of Enterprise Development in Product Development.","show_all_inline_media":false,"geo_enabled":false,"favourites_count":0,"profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_image_url":"http:\/\/a3.twimg.com\/profile_images\/1014488319\/Official_VA_Seal_embossed_web_1-25in_normal.gif","id_str":"158443688","listed_count":11,"notifications":null,"profile_use_background_image":true,"followers_count":126,"location":"Washington, DC","screen_name":"VA_OIT_PD","profile_background_color":"C0DEED","lang":"en","statuses_count":324,"profile_background_image_url":"http:\/\/a3.twimg.com\/profile_background_images\/171951175\/twitt_bar_VA_Vert_PD.jpg","url":"http:\/\/www.va.gov\/","friends_count":149,"protected":false,"is_translator":false,"profile_text_color":"333333","name":"VA OIT PD","following":null,"profile_sidebar_fill_color":"DDEEF6","id":158443688,"verified":false,"profile_background_tile":false,"time_zone":"Pacific Time (US & Canada)","utc_offset":-28800,"created_at":"Tue Jun 22 18:19:52 +0000 2010"},"in_reply_to_user_id":null,"truncated":false,"id":12936687013335041,"text":"House Vets panel gets new chair, but who else? - http:\/\/bit.ly\/fFcb9K #VA #Veterans #Military","created_at":"Thu Dec 09 18:28:41 +0000 2010"},{"place":null,"favorited":false,"in_reply_to_screen_name":null,"in_reply_to_status_id_str":null,"id_str":"12915900550221824","geo":null,"contributors":null,"retweet_count":0,"source":"\u003Ca href=\"http:\/\/bit.ly\" rel=\"nofollow\"\u003Ebitly\u003C\/a\u003E","in_reply_to_user_id_str":null,"coordinates":null,"retweeted":false,"in_reply_to_status_id":null,"user":{"follow_request_sent":null,"contributors_enabled":false,"description":"Official Twitter account of VA's Office of Enterprise Development in Product Development.","show_all_inline_media":false,"geo_enabled":false,"favourites_count":0,"profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_image_url":"http:\/\/a3.twimg.com\/profile_images\/1014488319\/Official_VA_Seal_embossed_web_1-25in_normal.gif","id_str":"158443688","listed_count":11,"notifications":null,"profile_use_background_image":true,"followers_count":126,"location":"Washington, DC","screen_name":"VA_OIT_PD","profile_background_color":"C0DEED","lang":"en","statuses_count":324,"profile_background_image_url":"http:\/\/a3.twimg.com\/profile_background_images\/171951175\/twitt_bar_VA_Vert_PD.jpg","url":"http:\/\/www.va.gov\/","friends_count":149,"protected":false,"is_translator":false,"profile_text_color":"333333","name":"VA OIT PD","following":null,"profile_sidebar_fill_color":"DDEEF6","id":158443688,"verified":false,"profile_background_tile":false,"time_zone":"Pacific Time (US & Canada)","utc_offset":-28800,"created_at":"Tue Jun 22 18:19:52 +0000 2010"},"in_reply_to_user_id":null,"truncated":false,"id":12915900550221824,"text":"Have you heard? The New House VA Committee Chair is Rep. Jeff Miller, R-Fla. #VA #Veterans #Govt","created_at":"Thu Dec 09 17:06:05 +0000 2010"},{"in_reply_to_status_id_str":null,"id_str":"12868872419934208","geo":null,"contributors":null,"retweet_count":0,"in_reply_to_user_id_str":null,"coordinates":null,"retweeted":false,"in_reply_to_status_id":null,"source":"\u003Ca href=\"http:\/\/bit.ly\" rel=\"nofollow\"\u003Ebitly\u003C\/a\u003E","user":{"id_str":"158443688","listed_count":11,"notifications":null,"profile_use_background_image":true,"followers_count":126,"location":"Washington, DC","screen_name":"VA_OIT_PD","profile_background_color":"C0DEED","lang":"en","statuses_count":324,"profile_background_image_url":"http:\/\/a3.twimg.com\/profile_background_images\/171951175\/twitt_bar_VA_Vert_PD.jpg","url":"http:\/\/www.va.gov\/","friends_count":149,"is_translator":false,"profile_text_color":"333333","following":null,"profile_sidebar_fill_color":"DDEEF6","verified":false,"profile_background_tile":false,"time_zone":"Pacific Time (US & Canada)","created_at":"Tue Jun 22 18:19:52 +0000 2010","protected":false,"follow_request_sent":null,"contributors_enabled":false,"description":"Official Twitter account of VA's Office of Enterprise Development in Product Development.","name":"VA OIT PD","show_all_inline_media":false,"geo_enabled":false,"favourites_count":0,"profile_link_color":"0084B4","id":158443688,"utc_offset":-28800,"profile_sidebar_border_color":"C0DEED","profile_image_url":"http:\/\/a3.twimg.com\/profile_images\/1014488319\/Official_VA_Seal_embossed_web_1-25in_normal.gif"},"in_reply_to_user_id":null,"truncated":false,"text":"VA hosts forum on homeless Veterans - http:\/\/www.examiner.com\/veterans-policy-in-national\/va-hosts-forum-on-homeless-veterans #VA #Veterans","created_at":"Thu Dec 09 13:59:12 +0000 2010","place":null,"favorited":false,"id":12868872419934208,"in_reply_to_screen_name":null}]);